# Зоны лимитов для различных сервисов
limit_req_zone $binary_remote_addr zone=auth_limit:10m  rate=400r/m;   # для сервиса авторизации (/auth/)
limit_req_zone $binary_remote_addr zone=api_limit:10m   rate=100r/m;  # для API (/api/)
limit_req_zone $binary_remote_addr zone=admin_limit:10m rate=50r/m;   # для админки Django (/admin/ и /)
limit_req_zone $binary_remote_addr zone=ugc_limit:10m   rate=300r/m;  # для UGC API (/ugc/)

# Код ответа при превышении лимита
limit_req_status 429;