# Обход блокировоки pipy.org Роскомнадзором
# Из всех IP на которые ресолвится pypi.org, работает только 151.101.0.223, прибиваем его гвоздями

services:
  movies-activity-tracker-service:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-admin-panel-service:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-alerting-engine:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-alerting-migrations:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-auth-service:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-community-content-service:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-films-etl-service:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-films-search-service:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-email-sender-1:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-email-sender-2:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-migrations:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-publisher:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-rabbit-init:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-recovery:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-scheduler:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-notifications-ws-gateway:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
  movies-superset:
    build:
      extra_hosts:
        - "pypi.org:151.101.0.223"
        - "files.pythonhosted.org:151.101.0.223"
