"""add unique constraint on user_roles (user_id, role_id)

Revision ID: e7d3adf85da9
Revises: f4472c503e14
Create Date: 2026-03-10 16:36:40.744683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d3adf85da9'
down_revision: Union[str, Sequence[str], None] = 'f4472c503e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_name', 'roles', ['name'], schema='auth')
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'], schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', schema='auth', type_='unique')
    op.drop_constraint('uq_role_name', 'roles', schema='auth', type_='unique')
    # ### end Alembic commands ###
