"""add oauth metadata

Revision ID: ffddfa4b92cb
Revises: e7d3adf85da9
Create Date: 2026-03-19 15:53:50.687140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffddfa4b92cb'
down_revision: Union[str, Sequence[str], None] = 'e7d3adf85da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user'),
    schema='auth'
    )
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True), schema='auth')
    op.create_unique_constraint(None, 'users', ['email'], schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='auth', type_='unique')
    op.drop_column('users', 'email', schema='auth')
    op.drop_table('user_oauth_providers', schema='auth')
    # ### end Alembic commands ###
