ARG PYTHON_VERSION=3.12.13
FROM python:${PYTHON_VERSION}-slim

WORKDIR /opt/tests

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir poetry==2.3.4
ENV POETRY_VIRTUALENVS_CREATE=false
RUN poetry install --no-interaction --no-ansi --no-root

CMD ["pytest", "-v", "src"]