[uwsgi]
# Базовые настройки
socket = :8000
protocol = http
chdir = /opt/admin-panel-service
module = main.wsgi:application

# Безопасность
uid = www-data
gid = www-data
master = true
vacuum = true
die-on-term = true

# Производительность
processes = 4
threads = 8
max-requests = 1000
buffer-size = 32768

# Логи
logto = /var/log/uwsgi.log
disable-logging = false
log-format = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"